macr macr1
mov r1, r2
inc r1
jmp r3
endmacr
macr1
add r3, r4 ljkgdf;dfdfdfdfdfdflllllllfgshjkdkkdkdkdkdkdkdkdkdkdkdkdkdkdjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
label1: .data 5, 10, -3
;mov label1, r1
macr haviv
bne r23

dfg kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
endmacr
jmp label1
haviv
macr1
haviv